# fly.toml app configuration file generated for ifitu on 2024-02-24T22:02:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ifitu'
primary_region = 'iad'

[build]

[env]
  COORDINATOR_FLOWS = 'local_flows'
  ENV = 'staging'
  FINANCE_PAYMENTS = 'payments'
  GOOGLE_CLIENT_ID = 'id'
  GOOGLE_CLIENT_SECRET = 'secret'
  GRAPH_DB_ADDRESS = 'localhost:7474'
  REDIS_USERNAME = 'default'
  SESSION_SECRET_KEY = 'secret'
  SVC_GRPC_PORT = ':50001'
  SVC_HTTP_PORT = ':3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
